config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/', :to => 'users#index'

  resources :users, only: [:index, :show] do   
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:create, :destroy] # posts/post_id/comments/id
    end
  end

  put 'user/:user_id/post/:id/like', to: 'posts#like', as: 'like' 
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    # Define User abilities
    return unless user.present?

    if user.is? :admin
      can :manage, :all
    else
      can :destroy, Post do |post|
        post.author == user
      end

      can :destroy, Comment do |comment|
        comment.Author == user
      end

      can %i[read create like], :all
    end
  end

  # The first argument to `can` is the action you are giving the user
  # permission to do.
  # If you pass :manage it will apply to every action. Other common actions
  # here are :read, :create, :update and :destroy.
  #
  # The second argument is the resource the user can perform the action on.
  # If you pass :all it will apply to every resource. Otherwise pass a Ruby
  # class of the resource.
  #
  # The third argument is an optional hash of conditions to further filter the
  # objects.
  # For example, here the user can only update published articles.
  #
  #   can :update, Article, :published => true
  #
  # See the wiki for details:
  # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :text, presence: true

  belongs_to :author, class_name: 'User'
  belongs_to :post, counter_cache: :CommentsCounter
  def update_comments_counter
    if post.commentsCounter.nil?
      post.update(commentsCounter: 1)
    else
      post.CommentsCounter += 1
      post.update(commentsCounter: post.commentsCounter)
    end
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :Author, class_name: 'User'
  belongs_to :post, counter_cache: :LikesCounter

  def update_likes_counter
    if post.likesCounter.nil?
      post.update(LikesCounter: 1)
    else
      post.likesCounter += 1
      post.update(likesCounter: post.likesCounter)
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true
  validates :text, length: { maximum: 250 }
  validates :commentsCounter, :likesCounter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  belongs_to :author, class_name: 'User', counter_cache: :postsCounter
  has_many :likes, dependent: :delete_all
  has_many :comments, dependent: :delete_all

  def update_counter
    if author.postsCounter.nil?
      author.update(postsCounter: 1)
    else
      author.postsCounter += 1
      author.update(postsCounter: author.postsCounter)
    end
  end

  def recent_comments
    comments.limit(5).order(created_at: :desc)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  validates :name, presence: true, uniqueness: true
  validates :postsCounter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  has_many :comments, foreign_key: 'author_id', class_name: 'Comment'
  has_many :posts, foreign_key: 'author_id', class_name: 'Post'
  has_many :likes, foreign_key: 'author_id', class_name: 'Like'

  ROLES = %i[admin default].freeze
  

  def is?(requested_role)
    role == requested_role.to_s
  end

  def recent_posts
    posts.limit(3).order(created_at: :desc)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
    before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name email password password_confirmation])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @publisher = User.find(params[:user_id])
    @post = Post.find(params[:post_id])
    @comment = Comment.new(params[:comment].permit(:Text))
    @comment.Author_id = current_user.id
    @comment.post_id = @post.id
    if @comment.save
      @comment.update_comments_counter
      flash[:notice] = 'Comment successfully added'
    else
      flash[:notice] = 'Something went wrong'
    end
    redirect_to user_post_path(@publisher, @post)
  end

  def destroy
    @comment = Comment.find_by(id: params[:id])
    @comment.destroy
    flash[:notice] = 'The Comment was successfully destroyed.'
    redirect_to user_post_url(User.find(params[:user_id]), Post.find(params[:post_id]))
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  def index
    @user = User.includes(:posts).find(params[:user_id])
  end

  def show
    @user = User.find_by(id: params[:user_id])
    @post = @user.posts.includes(:comments, :likes).find(params[:id])
    @comments = Comment.all.where(post_id: params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.commentsCounter = 0
    @post.likesCounter = 0
    @post.author_id = 1
    if @post.save
      @post.update_counter
      flash[:notice] = 'Post successfully created'
      redirect_to user_post_path(id: @post.id, user_id: @post.author_id)
    else
      flash[:notice] = 'Something went wrong'
      render 'new'
    end
  end

  def like
    @user = User.find_by(id: params[:user_id])
    @post = Post.find_by(id: params[:id], author_id: params[:user_id])
    @like = Like.create(post_id: @post.id, Author_id: current_user.id)
    @like.update_likes_counter
    flash[:notice] = 'Like successfully added'
    redirect_to user_post_path(@user, @post)
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:notice] = 'The Post was successfully destroyed.'
    redirect_to user_posts_url
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # authenticate_user_before
  
  def index
    @users = User.all
  end

  def show
    @user = User.find_by(id: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<%= form_with model: [@user, @post, @post.comments.build] do |form| %>
  <%= form.text_area :Text, placeholder: 'Write a comment...', class:"form-control" %>
  <br>
  
  <%= form.submit class: 'btn btn-dark' %>
  <br>
<% end %>

app/views/layouts/_alert.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <strong><%= notice %></strong>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
      <%= link_to "Blog app", "/" , class: "navbar-brand"%>
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home", users_path , class: "nav-link active"%>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/4f02d055e5.js" crossorigin="anonymous"></script>
    <title>Blog App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <% if notice %>
    <%= render 'layouts/alert' %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: @post, url: user_posts_path) do |form| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this Post from being saved:</h2>

      <ul>
        <% @post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form.text_field :title, placeholder: 'Title...', class:"form-control" %>
  <br>
  <%= form.text_area :text, placeholder: 'Post content...', class:"form-control" %>
  <br>
  <%= form.submit class: 'btn btn-dark' %>
  <br>
<% end %>

app/views/posts/index.html.erb
<%= render 'users/user', user: @user%>
<div class="user">
<%= link_to 'New Post', new_user_post_path, class: 'btn btn-secondary' %>
</div>
<% @user.posts.each do |post| %>
<div class="post-with-comments">
  <%= link_to "Post #{post.id}", "/users/#{@user.id}/posts/#{post.id}", id: "post_#{post.id}", class: "fs-5" %>
  <p><%= post.text %> </p>
  <div class="likes-comments">
      <p>comments: <%= !post.commentsCounter ? 0 : post.commentsCounter %></p>
      <p>Likes: <%= !post.likesCounter ? 0 : post.likesCounter %></p>
  </div>
</div>
<div class="comments">
<h6>Comments:</h6>
<% post.recent_comments.each do |comment| %>
  <div class="comment">
    <p class="user-name"><%= User.find_by(id: comment.author_id).name %>: </p>
    <p class="ml-2"> <%= comment.text %> </p>
  </div>
<% end %>
</div>
<% end %>


app/views/posts/new.html.erb
<div class="form d-md-block">
<h1>New Post</h1>
<br>
<%= render 'form', friend: @post %>
<br>
<%= link_to 'Back', user_posts_path, class: 'btn btn-secondary' %>
</div>

app/views/posts/show.html.erb
<div class="all-post">
  <div class="post-header">
    <div class="post-info">
      <p>Post: #<%= @post.id %></p>
      <p>By: <%= @user.name %></p>
    </div>
    <div class="comments-likes">
      <p>comments: <%= !@post.commentsCounter ? 0 : @post.commentsCounter %></p>
      <p>Likes: <%= !@post.likesCounter ? 0 : @post.likesCounter %></p>
    </div>
  </div>
  <div class="post-text">
    <p><%= @post.text %></p>
  </div>
  <div>
  <div class="likes">
  <i class="far fa-thumbs-up"></i><%= button_to "Like", like_path(@user, @post), method: "put", class: 'btn btn-secondary'%>
  </div>
  <br>
  <div class="delete">
    <% if can? :destroy , @post %>
     <%= link_to 'Destroy', user_post_path(@user, @post), method: :delete, data: { confirm: 'Are you sure?' } %>
     <% end %>
    </div>
  </div>
</div>
<div class="create-comment">
<%= render 'comments/comment' %>
</div>
<div class="comments">
<% @comments.each do |comment| %>
  <div class="comment">
    <p class="user-name"><%= User.find_by(id: comment.author_id).name %>: </p>
    <p class="ml-2"> <%= comment.text %> </p>
    <div>
    <% if can? :destroy, comment %>
        <%= button_to "Delete", user_post_comment_path(@user, @post, comment), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger"%>
        <% end %>
    </div>
  </div>
<% end %>
</div>

app/views/users/_user.html.erb
<div class="user">
  <div class="profile-image">
  <img class="img" src=<%= user.photo%> alt=<%= user.photo%>/>
  </div>
  <div class="user-info">
    <%= link_to "#{user.name}", "/users/#{user.id}", id: "user_#{user.id}", class: "fs-5" %>
    <div class="num-posts">
      <p>Number of posts: <%= user.postsCounter %> </p>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% @users.each do |user| %>
<%= render user, user: user%>
<% end %>

  

app/views/users/show.html.erb
<div class="user">
  <div class="profile-image">
  </div>
  <div class="user-info">
    <p class="fs-5"><%= @user.name %></p>
    <div class="num-posts">
      <p>Number of posts: <%= !@user.postsCounter ? 0 : @user.postsCounter %> </p>
    </div>
  </div>
</div>
<div class="bio">
  <p class="fs-4">Bio</p>
  <p><%= @user.bio %></p>
</div>
<% @user.recent_posts.each do |post| %>
<div class="post">
  <%= link_to "Post #{post.id}", "/users/#{@user.id}/posts/#{post.id}", class: "fs-5" %>
  <p><%= post.text %> </p>
</div>
<% end %>
<div class="see-posts">
  <%# <button class="btn btn-outline-dark"></button> %>
  <%= link_to 'See All The Posts', "/users/#{@user.id}/posts" %>
  <br>
</div>

